version: '3.8'

services:
  webapp:
    build: ./compute
    ports:
      - "5000:5000"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./network/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
