# vms/vm1/Vagrantfile

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"  # ✅ THIS LINE IS ESSENTIAL
    config.vm.hostname = "vm1"
    config.vm.network "private_network", ip: "192.168.56.10"
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
  end